version: '3.8'

services:
  # FlowBit Production Application
  flowbit-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: flowbit-prod
    ports:
      - "127.0.0.1:8000:8000"  # Bind to localhost only for security
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - DATABASE_URL=sqlite:///./data/flowbit.db
      - CRM_ENDPOINT=http://mockserver:8001/crm
      - RISK_ALERT_ENDPOINT=http://mockserver:8002/risk
      - COMPLIANCE_ENDPOINT=http://mockserver:8003/compliance
      - NOTIFICATION_ENDPOINT=http://mockserver:8004/notify
      - DEBUG=false
      - LOG_LEVEL=WARNING
      - MAX_UPLOAD_SIZE=10485760
      - WORKERS=4
    volumes:
      - flowbit-data:/app/data
      - flowbit-logs:/app/logs
    depends_on:
      - mockserver
    restart: always
    networks:
      - flowbit-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

  # Production Mock Services
  mockserver:
    image: nginx:alpine
    container_name: flowbit-mockserver-prod
    ports:
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8002:8002"
      - "127.0.0.1:8003:8003"
      - "127.0.0.1:8004:8004"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/mock-responses:/usr/share/nginx/html:ro
    networks:
      - flowbit-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  # Reverse Proxy (Production)
  nginx-proxy:
    image: nginx:alpine
    container_name: flowbit-nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx-proxy.conf:/etc/nginx/nginx.conf:ro
      - ./docker/ssl:/etc/nginx/ssl:ro  # For SSL certificates
    depends_on:
      - flowbit-app
    networks:
      - flowbit-network
    restart: always
    profiles:
      - proxy

  # Log Management
  logrotate:
    image: alpine:latest
    container_name: flowbit-logrotate
    volumes:
      - flowbit-logs:/logs
    command: |
      sh -c "
        while true; do
          find /logs -name '*.log' -size +100M -exec truncate -s 0 {} \;
          sleep 3600
        done
      "
    restart: always
    profiles:
      - logging

volumes:
  flowbit-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/flowbit/data  # Production data path
  flowbit-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/log/flowbit  # Production logs path

networks:
  flowbit-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 